module.exports = {
    ITEM_PER_PAGE: 6,
    TOTAL_PAGING_LINK: 3,
    PERFUME_START_ID_KEY: "PE",
    EYESHADOW_START_ID_KEY: "ES",
    BLOCK_LIPSTICK_START_ID_KEY: "LI",
    MASCARA_START_ID_KEY: "MA",
    POWDER_START_ID_KEY: "PO",
    PRIMER_START_ID_KEY: "PR",
    SERUM_START_ID_KEY: "SE",
    SKINCARE_START_ID_KEY: "SK",

    PAY_BY_CASH: 2,
    PAY_BY_MOMO: 4,
    PAY_BY_ZALOPAY: 3
}